defines:
  GL_ES: 1
  GLSL_VERSION: 300

uniforms:
  u_time: 0.0
  u_resolution: [800, 600]
  u_numBubbles: 6
  u_edgeThickness: 8.0
  u_bubbleColors[0]: [0.0, 0.0, 0.0]
  u_bubbleColors[1]: [0.0, 0.0, 0.0]
  u_bubbleColors[2]: [0.0, 0.0, 0.0]
  u_bubbleColors[3]: [0.0, 0.0, 0.0]
  u_bubbleColors[4]: [0.0, 0.0, 0.0]
  u_bubbleColors[5]: [0.0, 0.0, 0.0]
  u_bubbleRadii[0]: 0.0
  u_bubbleRadii[1]: 0.0
  u_bubbleRadii[2]: 0.0
  u_bubbleRadii[3]: 0.0
  u_bubbleRadii[4]: 0.0
  u_bubbleRadii[5]: 0.0
  u_bubblePositions[0]: [400.0, 300.0]
  u_bubblePositions[1]: [400.0, 300.0]
  u_bubblePositions[2]: [400.0, 300.0]
  u_bubblePositions[3]: [400.0, 300.0]
  u_bubblePositions[4]: [400.0, 300.0]
  u_bubblePositions[5]: [400.0, 300.0]